[platformio]
default_envs = nodemcuv2

[env:nodemcuv2]
platform = espressif8266@4.2.1
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 115200
lib_deps = waspinator/AccelStepper@1.64
build_flags = -Wall -Wextra

[env:native]
platform = native@1.2.1
test_framework = unity
build_flags = -std=c++11 -Wall -Wextra
